name: Learn basic of GitHub Action
on:
  push:
    branches:
      -  main

env: 
    JDK_VERSION: "openjdk11-jdk"
jobs:
  install-java:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: install java
        run: |
              apk add --no-cache openjdk11-jdk
              java --version

  print-env:
     runs-on: ubuntu-latest
     container:
      image:apline:latest
     steps:
      - name: print environment variable
        run: echo JDK_VERSION
     
